using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace CloudMesh.Mediator.SourceGenerator;

/// <summary>Turns the discovered value-equatable model into generated C# and diagnostics.</summary>
internal static class Emitter
{
    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
    }

    public static void Emit(
        SourceProductionContext spc,
        EquatableArray<RegistrationInfo> registrations,
        EquatableArray<RequestTypeInfo> requestTypesRaw,
        EquatableArray<NotificationTypeInfo> notificationTypesRaw,
        string assemblySuffix,
        Func<LocationInfo?, Location> toLocation)
    {
        // Deterministic, machine-independent ordering by a content key (never source file path).
        var distinctRegistrations = registrations
            .Distinct()
            .OrderBy(r => r.ImplementationType, StringComparer.Ordinal)
            .ThenBy(r => r.MessageType, StringComparer.Ordinal)
            .ThenBy(r => r.ResponseType ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(r => (int)r.Kind)
            .ToList();

        var requestTypes = requestTypesRaw
            .Distinct()
            .OrderBy(r => r.RequestType, StringComparer.Ordinal)
            .ThenBy(r => r.ResponseType, StringComparer.Ordinal)
            .ToList();

        var notificationTypes = notificationTypesRaw
            .Distinct()
            .OrderBy(n => n.NotificationType, StringComparer.Ordinal)
            .ToList();

        ReportDiagnostics(spc, distinctRegistrations, requestTypes, notificationTypes, toLocation);

        // Compute which request types are known to have NO pipeline behaviors at compile time, so the generated
        // overload can down-cast a concrete Mediator receiver to devirtualize the primitive call. Any open-generic
        // behavior applies to EVERY request of its kind, which disqualifies the down-cast for all of them
        // (correctness: the runtime behavior-presence check still runs either way, but this keeps the emitted code
        // honest about when the receiver is known to be behavior-free at compile time).
        var anyOpenSendBehavior = distinctRegistrations.Any(r => r.Kind == RegistrationKind.OpenGenericPipelineBehavior);
        var anyOpenStreamBehavior = distinctRegistrations.Any(r => r.Kind == RegistrationKind.OpenGenericStreamPipelineBehavior);

        var sendBehaviorMessages = new HashSet<string>(
            distinctRegistrations.Where(r => r.Kind == RegistrationKind.PipelineBehavior).Select(r => r.MessageType),
            StringComparer.Ordinal);
        var streamBehaviorMessages = new HashSet<string>(
            distinctRegistrations.Where(r => r.Kind == RegistrationKind.StreamPipelineBehavior).Select(r => r.MessageType),
            StringComparer.Ordinal);

        bool NoCompileTimeBehaviors(RequestTypeInfo r)
        {
            if (r.IsStream)
                return !anyOpenStreamBehavior && !streamBehaviorMessages.Contains(r.RequestType);
            return !anyOpenSendBehavior && !sendBehaviorMessages.Contains(r.RequestType);
        }

        spc.AddSource("CloudMeshMediatorRegistration.g.cs", EmitRegistration(distinctRegistrations, assemblySuffix));
        spc.AddSource("CloudMeshMediatorSenderExtensions.g.cs", EmitSenderOverloads(requestTypes, assemblySuffix, NoCompileTimeBehaviors));
    }

    // ------------------------------------------------------------------ diagnostics
    private static void ReportDiagnostics(
        SourceProductionContext spc,
        List<RegistrationInfo> registrations,
        List<RequestTypeInfo> requestTypes,
        List<NotificationTypeInfo> notificationTypes,
        Func<LocationInfo?, Location> toLocation)
    {
        // Key handler presence on the (request, response) PAIR — not the request alone. A request may implement
        // IRequest<A> AND IRequest<B> with a distinct handler per response; the runtime dispatches on the
        // (TRequest,TResponse) pair and DI keys on the closed handler interface, so that is legal, not a duplicate.
        var requestHandlerImpls = new Dictionary<(string, string), List<string>>();
        var streamHandlerImpls = new Dictionary<(string, string), List<string>>();
        var notificationHandlerMessages = new HashSet<string>(StringComparer.Ordinal);

        foreach (var reg in registrations)
        {
            switch (reg.Kind)
            {
                case RegistrationKind.RequestHandler:
                case RegistrationKind.CompatRequestHandler:
                    Add(requestHandlerImpls, (reg.MessageType, reg.ResponseType ?? string.Empty), reg.ImplementationType);
                    break;
                case RegistrationKind.StreamRequestHandler:
                    Add(streamHandlerImpls, (reg.MessageType, reg.ResponseType ?? string.Empty), reg.ImplementationType);
                    break;
                case RegistrationKind.NotificationHandler:
                case RegistrationKind.CompatNotificationHandler:
                    notificationHandlerMessages.Add(reg.MessageType);
                    break;
            }
        }

        foreach (var req in requestTypes)
        {
            var impls = req.IsStream ? streamHandlerImpls : requestHandlerImpls;
            var location = toLocation(req.Location);
            var key = (req.RequestType, req.ResponseType);

            if (!impls.TryGetValue(key, out var handlers) || handlers.Count == 0)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.MissingRequestHandler, location, Simplify(req.RequestType)));
            }
            else if (handlers.Count > 1)
            {
                var names = string.Join(", ", handlers.Select(Simplify).OrderBy(x => x, StringComparer.Ordinal));
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DuplicateRequestHandler, location,
                    Simplify(req.RequestType), Simplify(req.ResponseType), handlers.Count, names));
            }
        }

        foreach (var note in notificationTypes)
        {
            if (!notificationHandlerMessages.Contains(note.NotificationType))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.NotificationWithoutHandlers, toLocation(note.Location), Simplify(note.NotificationType)));
            }
        }

        // CMED100: MediatR-compat shim handler usage. Reported once per compat handler type, on its declaration.
        foreach (var reg in registrations)
        {
            if (reg.Kind is RegistrationKind.CompatRequestHandler or RegistrationKind.CompatNotificationHandler)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.CompatShimHandler, toLocation(reg.Location), Simplify(reg.ImplementationType)));
            }
        }

        static void Add(Dictionary<(string, string), List<string>> map, (string, string) key, string value)
        {
            if (!map.TryGetValue(key, out var list))
                map[key] = list = new List<string>();
            list.Add(value);
        }
    }

    // ------------------------------------------------------------------ registration
    private static string EmitRegistration(List<RegistrationInfo> registrations, string suffix)
    {
        var sb = new StringBuilder();
        AppendHeader(sb);
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Source-generated, reflection-free registration for CloudMesh.Mediator.</summary>");
        sb.AppendLine("    public static class CloudMeshMediatorGeneratedExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers the mediator infrastructure and every handler/behavior discovered in THIS assembly");
        sb.AppendLine("        /// at compile time. No assembly scanning and no reflection; AOT/trim friendly.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <remarks>");
        sb.AppendLine("        /// Each assembly that references CloudMesh.Mediator gets its OWN uniquely-named registration");
        sb.AppendLine($"        /// method (suffixed with the assembly name). An app composes them, e.g.");
        sb.AppendLine("        /// <c>services.AddCloudMeshMediatorGeneratedContracts().AddCloudMeshMediatorGeneratedMyApp();</c>");
        sb.AppendLine("        /// Handlers whose type (or its request/response) is not at least internally accessible are omitted,");
        sb.AppendLine("        /// since generated code could not reference them.");
        sb.AppendLine("        /// </remarks>");
        sb.AppendLine($"        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddCloudMeshMediatorGenerated{suffix}(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine("            global::System.Action<global::CloudMesh.Mediator.MediatorOptions>? configure = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var options = new global::CloudMesh.Mediator.MediatorOptions();");
        sb.AppendLine("            configure?.Invoke(options);");
        sb.AppendLine();
        sb.AppendLine("            // Shared infrastructure registration (mediator, runtime cache, notification publisher).");
        sb.AppendLine("            global::CloudMesh.Mediator.MediatorServiceCollectionExtensions.AddCloudMeshMediatorCore(services, options);");
        sb.AppendLine();
        sb.AppendLine("            var lifetime = options.HandlerLifetime;");

        if (registrations.Count == 0)
        {
            sb.AppendLine("            // No handlers or behaviors were discovered in this compilation.");
        }
        else
        {
            sb.AppendLine();
            foreach (var reg in registrations)
                EmitOneRegistration(sb, reg);
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitOneRegistration(StringBuilder sb, RegistrationInfo reg)
    {
        switch (reg.Kind)
        {
            case RegistrationKind.RequestHandler:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.IRequestHandler<{reg.MessageType}, {reg.ResponseType}>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.StreamRequestHandler:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.IStreamRequestHandler<{reg.MessageType}, {reg.ResponseType}>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.NotificationHandler:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.INotificationHandler<{reg.MessageType}>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.PipelineBehavior:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.IPipelineBehavior<{reg.MessageType}, {reg.ResponseType}>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.StreamPipelineBehavior:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.IStreamPipelineBehavior<{reg.MessageType}, {reg.ResponseType}>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.OpenGenericPipelineBehavior:
                // Open-generic descriptor; MS DI closes it per request type at resolution.
                AddDescriptor(sb,
                    "global::CloudMesh.Mediator.IPipelineBehavior<,>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.OpenGenericStreamPipelineBehavior:
                AddDescriptor(sb,
                    "global::CloudMesh.Mediator.IStreamPipelineBehavior<,>",
                    reg.ImplementationType);
                break;

            case RegistrationKind.CompatRequestHandler:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.Compatibility.IRequestHandler<{reg.MessageType}, {reg.ResponseType}>",
                    reg.ImplementationType);
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.IRequestHandler<{reg.MessageType}, {reg.ResponseType}>",
                    $"global::CloudMesh.Mediator.Compatibility.CompatRequestHandlerAdapter<{reg.MessageType}, {reg.ResponseType}>");
                break;

            case RegistrationKind.CompatNotificationHandler:
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.Compatibility.INotificationHandler<{reg.MessageType}>",
                    reg.ImplementationType);
                AddDescriptor(sb,
                    $"global::CloudMesh.Mediator.INotificationHandler<{reg.MessageType}>",
                    $"global::CloudMesh.Mediator.Compatibility.CompatNotificationHandlerAdapter<{reg.MessageType}>");
                break;
        }
    }

    private static void AddDescriptor(StringBuilder sb, string serviceType, string implementationType)
    {
        sb.AppendLine(
            $"            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(" +
            $"typeof({serviceType}), typeof({implementationType}), lifetime));");
    }

    // ------------------------------------------------------------------ sender overloads
    private static string EmitSenderOverloads(
        List<RequestTypeInfo> requestTypes, string suffix, Func<RequestTypeInfo, bool> noCompileTimeBehaviors)
    {
        var sb = new StringBuilder();
        AppendHeader(sb);
        sb.AppendLine();
        sb.AppendLine("namespace CloudMesh.Mediator");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Source-generated, zero-boxing ergonomic overloads. For each concrete request type these bind more");
        sb.AppendLine("    /// specifically than the interface-typed ISender.SendAsync overload, so sending a struct request");
        sb.AppendLine("    /// takes the box-free path. Internal request/response types get internal overloads.");
        sb.AppendLine("    /// When the generator saw no pipeline behaviors for a request type, the overload down-casts a concrete");
        sb.AppendLine("    /// runtime Mediator receiver and calls the box-free primitive on it, which the JIT devirtualizes (there is");
        sb.AppendLine("    /// no special dispatch path — the same runtime behavior-presence check still runs, so runtime-registered");
        sb.AppendLine("    /// behaviors are honored); a custom ISender takes the interface call unchanged.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class CloudMeshMediatorSenderExtensions{suffix}");
        sb.AppendLine("    {");

        var first = true;
        foreach (var req in requestTypes)
        {
            // Effective access below Internal => cannot even name the type from an assembly-level class -> skip.
            if (req.EffectiveAccess < Access.Internal)
                continue;

            // internal request/response => the overload must be internal (public would leak an inaccessible type: CS0051).
            var visibility = req.EffectiveAccess >= Access.Public ? "public" : "internal";
            var shortName = ShortName(req.RequestType);
            var devirtualize = noCompileTimeBehaviors(req);
            var method = req.IsStream ? "StreamAsync" : "SendAsync";
            var returnType = req.IsStream
                ? $"global::System.Collections.Generic.IAsyncEnumerable<{req.ResponseType}>"
                : $"global::System.Threading.Tasks.ValueTask<{req.ResponseType}>";
            var verb = req.IsStream ? "Streams" : "Sends";

            if (!first)
                sb.AppendLine();
            first = false;

            sb.AppendLine($"        /// <summary>{verb} a {shortName} request with no boxing.</summary>");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"        {visibility} static {returnType} {method}(");
            sb.AppendLine("            this global::CloudMesh.Mediator.ISender sender,");
            sb.AppendLine($"            in {req.RequestType} request,");
            sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken = default)");
            EmitBody(sb, method, req.RequestType, req.ResponseType, devirtualize);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Emits the expression body. When the generator saw no behaviors, it down-casts a concrete Mediator receiver
    // and calls the same box-free primitive on it (JIT devirtualizes the sealed-type call — no special path);
    // otherwise it goes straight through the interface. Identical semantics either way.
    private static void EmitBody(StringBuilder sb, string method, string requestType, string responseType, bool devirtualize)
    {
        var primitive = $"{method}<{requestType}, {responseType}>(in request, cancellationToken)";
        if (devirtualize)
        {
            sb.AppendLine("            => sender is global::CloudMesh.Mediator.Mediator __m");
            sb.AppendLine($"                ? __m.{primitive}");
            sb.AppendLine($"                : sender.{primitive};");
        }
        else
        {
            sb.AppendLine($"            => sender.{primitive};");
        }
    }

    // ------------------------------------------------------------------ helpers
    private static string Simplify(string fullyQualified)
        // Strip ALL global:: occurrences (including inside generic args) for readable diagnostics.
        => fullyQualified.Replace("global::", string.Empty);

    /// <summary>A short, human-friendly type name (no global::, no namespace) for doc summaries.</summary>
    private static string ShortName(string fullyQualified)
    {
        var s = fullyQualified.Replace("global::", string.Empty);
        var lt = s.IndexOf('<');
        var head = lt >= 0 ? s.Substring(0, lt) : s;
        var dot = head.LastIndexOf('.');
        var simpleHead = dot >= 0 ? head.Substring(dot + 1) : head;
        return lt >= 0 ? simpleHead + s.Substring(lt) : simpleHead;
    }
}
