name: Build
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: Build & Pack
    runs-on: ubuntu-latest
    steps:
      

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build Actors
      run: dotnet build src/CloudMesh.Actors/CloudMesh.Actors.csproj -c Release /p:CI=true

    - name: Build Actors.Aws
      run: dotnet build src/CloudMesh.Actors.Aws/CloudMesh.Actors.Aws.csproj -c Release /p:CI=true

    - name: Build CloudMesh.Actors.Hosting
      run: dotnet build src/CloudMesh.Actors.Hosting/CloudMesh.Actors.Hosting.csproj -c Release /p:CI=true

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate -ApiKey ${{secrets.NUGET_KEY}}
    