name: Publish
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  TERM: xterm

jobs:
  publish:
    name: Build & Test & Publish
    runs-on: ubuntu-latest
    steps:
      
      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set version
      run: echo "VERSION=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Print version
      run: echo "Building $VERSION"

    - name: Test
      run: dotnet test

    - name: Clean
      run: dotnet clean

    - name: Build all in release mode
      run: dotnet build CloudMesh.sln -c Release /p:CI=true /p:Version=$VERSION

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate -ApiKey ${{secrets.NUGET_KEY}}
    