name: Publish to Nuget
on:
  push:
    branches:
      - main # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

    - name: Checkout code
      uses: actions/checkout@v1
    - name: Where am I
      run: pwd
    - name: What is here
      run: ls -la
    - name: .NET Build Actors
      run: dotnet build src/CloudMesh.Actors.csproj -c Release /p:CI=true
    - name: .NET Lib Pack
      run: dotnet pack src/CloudMesh.Actors.csproj --no-build -c Release /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true