name: Build
on:
  push:
    branches-ignore: 
      - 'main'
    
jobs:
  tests-dotnet8:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      
      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Set version
      run: echo "VERSION=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Test
      run: dotnet test -f net8.0
      
  tests-dotnet9:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      
      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      - name: Checkout code
        uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set version
        run: echo "VERSION=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Test
        run: dotnet test -f net9.0