name: Publish to Nuget
on:
  release:
    types: [published]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: .NET Build Actors
      run: dotnet build src/CloudMesh.Actors/CloudMesh.Actors.csproj -c Release /p:CI=true

    - name: Publish CloudMesh.Actors
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/CloudMesh.Actors/CloudMesh.Actors.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    # - name: Publish
    #  if: startsWith(github.ref, 'refs/heads/release')
    #  run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_KEY}}
    
    #- name: .NET Lib Pack
    #  run: dotnet pack src/CloudMesh.Actors/CloudMesh.Actors.csproj --no-build -c Release /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true